services:
  postgres-db:
    image: postgres:alpine
    container_name: noticias-database
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres_db_data:/var/lib/postgresql/data

  noticias-back:
    build:
      context: .
      target: base
    image: noticias-dev
    container_name: noticias-backend
    depends_on:
      - postgres-db
    ports:
      - ${PORT}:${PORT}
      - 24678:24678
    expose:
      - ${PORT}
    env_file:
      - .env
    environment:
      - DB_HOST=postgres-db
    volumes:
      - ./:/home/node/app
    entrypoint: >
      sh -c 
      "npm i &&
      node ace serve --watch --poll"

volumes:
  postgres_db_data:
