version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - noticias_mysql_volume:/var/lib/mysql

  redisdb:
    image: redis:alpine
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - noticias_redis_volume:/data

  backend:
    depends_on:
      - mysqldb
      - redisdb
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 8080:8080
      - 9229:9229
    env_file:
      - .env
    environment:
      MYSQL_HOST: mysqldb
    volumes:
      - ./:/home/node/app
    healthcheck:
      test: curl --fail http://localhost:${PORT}/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    command: node ace serve --watch --encore-args="--host ${HOST} --port 8080"

volumes:
  noticias_mysql_volume:
  noticias_redis_volume:
