# the lightsail instance has redis and to lower resources consumptions uses sqlite
version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./tmp:/home/node/app/tmp
    restart: always
    healthcheck:
      test: curl --fail http://localhost:${PORT}/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
