version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mysql_volume:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10

  redisdb:
    image: redis:alpine
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - redis_volume:/data

  backend:
    depends_on:
      mysqldb:
        condition: service_healthy
      redisdb:
        condition: service_started
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 8080:8080
      - 9229:9229
    env_file:
      - .env
    environment:
      DB_CONNECTION: mysql
      MYSQL_HOST: mysqldb
      REDIS_HOST: redisdb
    volumes:
      - ./:/home/node/app
    healthcheck:
      test: curl --fail http://localhost:${PORT}/health || exit 1
      interval: 30s
      retries: 5
      start_period: 60s
      timeout: 5s
    command: node ace serve --watch --encore-args="--host ${HOST} --port 8080"

volumes:
  mysql_volume:
  redis_volume:
